# fly.toml app configuration file generated for weasyprint on 2026-02-13T14:54:59-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weasyprint'
primary_region = 'ord'

[build]
  image = 'ghcr.io/bcgov/weasyprint:latest'

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
